apply plugin: "java-library"

sourceCompatibility = 1.8
targetCompatibility = 1.8

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
}

dependencies {
    implementation project(":core")
    api "com.badlogicgames.gdx:gdx-backend-lwjgl3:1.11.0"
    api "com.badlogicgames.gdx:gdx-platform:1.11.0:natives-desktop"
    api "com.badlogicgames.gdx:gdx-box2d-platform:1.11.0:natives-desktop"
}

task run(type: JavaExec) {
    main = "com.slidegame.game.DesktopLauncher"
    classpath = sourceSets.main.runtimeClasspath
    standardInput = System.in
    workingDir = project.file("../android/assets")
    ignoreExitValue = true

    if (org.gradle.internal.os.OperatingSystem.current().isMacOsX()) {
        jvmArgs '-XstartOnFirstThread'
    }
}
